const fs = require('fs');
const code = fs.readFileSync('js/language.js', 'utf8');
const transRegex = /const TRANSLATIONS = (\{[\s\S]*?\n\});/m;
const evalCode = code + '\nmodule.exports = TRANSLATIONS;';
const vm = require('vm');
const sandbox = { module: {} };
vm.createContext(sandbox);
vm.runInContext(evalCode, sandbox);
const trans = sandbox.module.exports;
const enKeys = Object.keys(trans.en);
const taKeys = Object.keys(trans.ta || {});
const hiKeys = Object.keys(trans.hi || {});
const taMissing = enKeys.filter(k => !trans.ta[k]);
const hiMissing = enKeys.filter(k => !trans.hi[k]);
console.log('English keys:', enKeys.length);
console.log('Tamil keys:', taKeys.length, 'Missing from English list:', taMissing.length);
if (taMissing.length > 0) console.log('Some missing TA:', taMissing.slice(0, 5));
console.log('Hindi keys:', hiKeys.length, 'Missing from English list:', hiMissing.length);
if (hiMissing.length > 0) console.log('Some missing HI:', hiMissing.slice(0, 5));
